---
name: Filter

on: push

jobs:
    test:
        name: Filter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: npm install -g karma
            - run: npm install -g karma-chrome-launcher
            - run: npm install -g karma-qunit
            - run: npm install -g qunitjs
            - run: pwd
            - run: cd ./WebImblaze-Framework/scripts/unitTests && karma start --single-run
